# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'firstorder.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(806, 721)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setBaseSize(QtCore.QSize(0, 0))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(640, 480))
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 120, 781, 581))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setAutoFillBackground(True)
        self.widget.setObjectName("widget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 30, 721, 521))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 781, 117))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.labelGain = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelGain.setObjectName("labelGain")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelGain)
        self.gain = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget)
        self.gain.setProperty("value", 1.0)
        self.gain.setObjectName("gain")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.gain)
        self.tau = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget)
        self.tau.setProperty("value", 1.0)
        self.tau.setObjectName("tau")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.tau)
        self.labelTau = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelTau.setObjectName("labelTau")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelTau)
        self.plotButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.plotButton.setObjectName("plotButton")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.plotButton)
        self.horizontalLayout.addLayout(self.formLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.navTools = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.navTools.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.navTools.setAutoFillBackground(True)
        self.navTools.setChecked(True)
        self.navTools.setObjectName("navTools")
        self.verticalLayout_3.addWidget(self.navTools)
        self.line = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.stepButton = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.stepButton.setObjectName("stepButton")
        self.verticalLayout_3.addWidget(self.stepButton)
        self.bodeButton = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.bodeButton.setObjectName("bodeButton")
        self.verticalLayout_3.addWidget(self.bodeButton)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "First Order LTI"))
        self.labelGain.setText(_translate("MainWindow", "Gain"))
        self.labelTau.setText(_translate("MainWindow", "Time Constant"))
        self.plotButton.setText(_translate("MainWindow", "Plot"))
        self.navTools.setStatusTip(_translate("MainWindow", "Enable the Plot Navigation Tools"))
        self.navTools.setWhatsThis(_translate("MainWindow", "The Plot Navigation Tools Enabler"))
        self.navTools.setText(_translate("MainWindow", "Navigation Tools"))
        self.stepButton.setText(_translate("MainWindow", "Step Response"))
        self.bodeButton.setText(_translate("MainWindow", "Bode Diagram"))

